"""
Django settings for radiantensemble project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import importlib.util
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_config():
    config_path = BASE_DIR / ".env" / "config.py"
    if not config_path.exists():
        return {}
    try:
        spec = importlib.util.spec_from_file_location("radiantensemble_local_config", config_path)
        if spec is None or spec.loader is None:
            return {}
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
    except Exception:
        return {}
    return {
        "CF_TURNSTILE_SITE_KEY": getattr(module, "CF_TURNSTILE_SITE_KEY", ""),
        "CF_TURNSTILE_SECRET_KEY": getattr(module, "CF_TURNSTILE_SECRET_KEY", ""),
        "CF_TURNSTILE_ENABLED": getattr(module, "CF_TURNSTILE_ENABLED", True),
        "DJANGO_DEBUG": getattr(module, "DJANGO_DEBUG", None),
        "DJANGO_SECRET_KEY": getattr(module, "DJANGO_SECRET_KEY", ""),
        "EMAIL_BACKEND": getattr(module, "EMAIL_BACKEND", ""),
        "EMAIL_HOST": getattr(module, "EMAIL_HOST", ""),
        "EMAIL_PORT": getattr(module, "EMAIL_PORT", None),
        "EMAIL_USE_TLS": getattr(module, "EMAIL_USE_TLS", None),
        "EMAIL_HOST_USER": getattr(module, "EMAIL_HOST_USER", ""),
        "EMAIL_HOST_PASSWORD": getattr(module, "EMAIL_HOST_PASSWORD", ""),
        "DEFAULT_FROM_EMAIL": getattr(module, "DEFAULT_FROM_EMAIL", ""),
        "SERVER_EMAIL": getattr(module, "SERVER_EMAIL", ""),
    }


_LOCAL_CONFIG = _load_local_config()


def _config_value(name, default=""):
    value = os.environ.get(name)
    if value not in (None, ""):
        return value
    value = _LOCAL_CONFIG.get(name)
    if value not in (None, ""):
        return value
    return default


def _config_bool(name, default=False):
    value = _config_value(name, default)
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _config_value(
    "DJANGO_SECRET_KEY",
    "django-insecure-=0i9l!$atp)6o-e(nbc98l)ks10lenn3^$@ch#hta)ckg_f5vo",
)
ARTIFACT_METADATA_HMAC_KEY = os.environ.get("ARTIFACT_METADATA_HMAC_KEY", SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _config_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = [
    "localhost",
    ".localhost",
    "127.0.0.1",
    "0.0.0.0",
    "testserver",
    "radiantensemble.com",
    "www.radiantensemble.com",
]

CSRF_TRUSTED_ORIGINS = [
    "https://radiantensemble.com",
    "https://www.radiantensemble.com",
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG


# Application definition

INSTALLED_APPS = [
    'community.apps.CommunityConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'radiantensemble.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'radiantensemble.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'frontend' / 'dist']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
LOGIN_URL = 'login'

CF_TURNSTILE_SITE_KEY = _LOCAL_CONFIG.get("CF_TURNSTILE_SITE_KEY", "")
CF_TURNSTILE_SECRET_KEY = _LOCAL_CONFIG.get("CF_TURNSTILE_SECRET_KEY", "")
CF_TURNSTILE_ENABLED = bool(_LOCAL_CONFIG.get("CF_TURNSTILE_ENABLED", True))

EMAIL_BACKEND = _config_value(
    "EMAIL_BACKEND",
    (
        "django.core.mail.backends.console.EmailBackend"
        if DEBUG
        else "django.core.mail.backends.smtp.EmailBackend"
    ),
)
EMAIL_HOST = _config_value("EMAIL_HOST", "localhost")
EMAIL_PORT = int(_config_value("EMAIL_PORT", 25))
EMAIL_USE_TLS = _config_bool("EMAIL_USE_TLS", False)
EMAIL_HOST_USER = _config_value("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = _config_value("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = _config_value(
    "DEFAULT_FROM_EMAIL",
    "Radiant Ensemble <mcarroll@radiantensemble.com>",
)
SERVER_EMAIL = _config_value("SERVER_EMAIL", "mcarroll@radiantensemble.com")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
