# Generated by Django 5.0 on 2026-06-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='repeat',
            field=models.CharField(choices=[('none', 'Does not repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly on same day of month'), ('monthly_ordinal', 'Monthly on same ordinal weekday')], default='none', max_length=20),
        ),
    ]
