# Generated by Django 5.0 on 2026-06-06 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_event_repeat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurrence_date', models.DateField()),
                ('cancelled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_event_occurrences', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='community.event')),
            ],
            options={
                'ordering': ['event', 'occurrence_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventcancellation',
            constraint=models.UniqueConstraint(fields=('event', 'occurrence_date'), name='unique_event_cancellation'),
        ),
    ]
