# Generated by Django 5.0 on 2026-06-08 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_bugreport_featurerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='contact_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='photo',
            field=models.FileField(blank=True, upload_to='member_photos/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='MemberProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='community.memberprofile')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
