# Generated by Django 5.0 on 2026-06-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_memberprofile_contact_info_memberprofile_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
