# Generated by Django 5.0 on 2026-06-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_remove_memberprofile_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artifact',
            name='metadata_signature',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='artifact',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='artifact',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artifact',
            name='sha256_checksum',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='artifact',
            name='signature_algorithm',
            field=models.CharField(default='hmac-sha256', max_length=50),
        ),
        migrations.AddField(
            model_name='artifact',
            name='stored_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
